import React from 'react';
import { Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { toVnd, useCartStore } from '@stores/cartStore';
import { useCampusLocation } from '@hooks/useCampusLocation';
import { ROOM_LABEL } from '@constants/student';
import { theme } from '@constants/theme';
import { formatVndValue } from '@components/ProductCard';
import { Watermark } from '@components/Watermark';

export default function CartScreen() {
  const { items, changeQty, remove, totalAmount } = useCartStore();
  const location = useCampusLocation();
  const goodsTotal = totalAmount();
  return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.heading}>GIỎ HÀNG</Text></View><ScrollView contentContainerStyle={styles.content}>{items.length === 0 ? <Text style={styles.empty}>Chưa có sản phẩm.</Text> : items.map((item) => <View key={item.id} style={styles.row}><Image source={{ uri: item.image }} style={styles.image} resizeMode="contain" /><View style={styles.info}><Text numberOfLines={2} style={styles.title}>{item.title}</Text><View style={styles.controls}><Pressable onPress={() => changeQty(item.id, item.quantity - 1)} style={styles.control} accessibilityLabel={`Giảm ${item.title}`}><Text style={styles.controlText}>−</Text></Pressable><Text style={styles.quantity}>{item.quantity}</Text><Pressable onPress={() => changeQty(item.id, item.quantity + 1)} style={styles.control} accessibilityLabel={`Tăng ${item.title}`}><Text style={styles.controlText}>+</Text></Pressable><Pressable onPress={() => remove(item.id)} style={styles.deleteButton} accessibilityLabel={`Xóa ${item.title}`}><Text style={styles.delete}>Xóa</Text></Pressable></View><Text style={styles.lineTotal}>{formatVndValue(toVnd(item.price) * item.quantity)}</Text></View></View>)}<View style={styles.summary}><Text style={styles.summaryText}>Giao đến {ROOM_LABEL}</Text>{location.fee !== null && <Text style={styles.shipFee}>Phí ship: {location.fee.toLocaleString('vi-VN')} đ</Text>}</View><Text style={styles.total}>Tổng hàng: {formatVndValue(goodsTotal)}</Text></ScrollView><Watermark fixed /></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: theme.background }, header: { padding: 14, alignItems: 'center', backgroundColor: theme.primary }, heading: { color: theme.surface, fontSize: 20, fontWeight: '900' }, content: { padding: 16, paddingBottom: 120 }, empty: { marginTop: 30, textAlign: 'center', color: theme.textLight }, row: { flexDirection: 'row', marginBottom: 10, padding: 10, borderRadius: 12, backgroundColor: theme.surface }, image: { width: 58, height: 58, borderRadius: 8, backgroundColor: theme.background }, info: { flex: 1, marginLeft: 10 }, title: { color: theme.text, fontWeight: '700', paddingRight: 8 }, controls: { flexDirection: 'row', alignItems: 'center', marginTop: 8 }, control: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 6, backgroundColor: theme.background }, controlText: { color: theme.primary, fontSize: 18, fontWeight: '700' }, quantity: { marginHorizontal: 10, color: theme.text, fontWeight: '700' }, deleteButton: { marginLeft: 'auto', padding: 4 }, delete: { color: theme.error, fontWeight: '700' }, lineTotal: { marginTop: 4, color: theme.primary, fontWeight: '800' }, summary: { marginTop: 4, padding: 14, borderRadius: 12, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.secondary }, summaryText: { color: theme.text, fontWeight: '700' }, shipFee: { marginTop: 7, color: theme.secondary, fontWeight: '800' }, total: { marginTop: 12, color: theme.primary, fontWeight: '900', fontSize: 16 } });
